<?php
/**
 * Aceextensions_OneStepCheckout
 *
 * @category    Checkout
 * @package     Aceextensions_OneStepCheckout
 * @author      Durga Shankar Gupta
 * @copyright   DreamWorkFactory (https://dreamworkfactory.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @var $block \Aceextensions\OneStepCheckout\Block\Adminhtml\Order\View\Comment
 */
?>
<?php if ($block->getOrderDateTime()): ?>
    <section class="admin__page-section onestepcheckout-delivery-date">
        <div class="admin__page-section-item-title">
            <span class="title"><?= __('Delivery Date') ?></span>
        </div>
        <div class="admin__page-section-item-content">
            <span class="comment"><?php echo $block->getOrderDateTime() ?></span>
        </div>
    </section>
<?php endif ?>
<?php if ($block->getOrderComment()): ?>
    <section class="admin__page-section onestepcheckout-comment">
        <div class="admin__page-section-item-title">
            <span class="title"><?= __('Delivery Comment') ?></span>
        </div>
        <div class="admin__page-section-item-content">
            <span class="comment"><?php echo $block->getOrderComment() ?></span>
        </div>
    </section>
<?php endif ?>
