<?php
/**
 * Aceextensions_OneStepCheckout
 *
 * @category    Checkout
 * @package     Aceextensions_OneStepCheckout
 * @author      Durga Shankar Gupta
 * @copyright   DreamWorkFactory (https://dreamworkfactory.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @var $block Magento\Framework\View\Element\AbstractBlock
 */
?>
<?php if ($block->getChildHtml()): ?>
    <div class="block block-order-additional-view">
        <div class="block-title">
            <strong><?php echo __('Additional Information') ?></strong>
        </div>
        <div class="block-content">
            <?php echo $block->getChildHtml() ?>
        </div>
    </div>
<?php endif; ?>
