<?php
/**
 * Aceextensions_OneStepCheckout
 *
 * @category    Checkout
 * @package     Aceextensions_OneStepCheckout
 * @author      Durga Shankar Gupta
 * @copyright   DreamWorkFactory (https://dreamworkfactory.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @var $block \Aceextensions\OneStepCheckout\Block\LayoutOnestepCheckout\Container
 */

 return;
// $themeSettingConfig = $this->helper('Aceextensions\ThemeSettings\Helper\Config');
// $layoutType = $themeSettingConfig->getStoreConfig('themesettings/page_title/design') ? $themeSettingConfig->getStoreConfig('themesettings/page_title/design') : 1;
$layoutType = 1;

$customClass = $customStyle = "";
$background = 2;
if($background == 2){
	/* Image */
	if($image = $themeSettingConfig->getStoreConfig('themesettings/page_title/background_image')){
		$customClass = "ttbg-image";
		if($themeSettingConfig->getStoreConfig('themesettings/page_title/bg_repeat')){
			$customClass .= " ttbg-image-repeat";
		}
		$imageBg = $themeSettingConfig->getPageTitleBackground();
		$customStyle = "background-image: url(".$imageBg.");";
	}
}elseif($themeSettingConfig->getStoreConfig('themesettings/page_title/background') == 3) {
	/* Color */
	if($color = $themeSettingConfig->getStoreConfig('themesettings/page_title/background_color')){
		$customClass = "ttbg-color";
		$customStyle = "background-color: ".$color.";";
	}
}
?>

<div class="page-title-wrapper" <?php if($layoutType == 1): ?> style="<?= $customStyle ?>"<?php endif ?>>
    <h1 class="checkout-title"><?php echo $block->getCheckoutTitle(); ?></h1>
    <p class="checkout-description">
        <?php echo $block->getCheckoutDescription(); ?>
    </p>
</div>

